/*
--    관리자 계정에서 MECENAT 계정 생성, 권한 부여
--    CREATE USER MECENAT IDENTIFIED BY MECENAT;
--    GRANT CONNECT, RESOURCE TO MECENAT;
*/

DROP TABLE REVIEW CASCADE CONSTRAINTS;
DROP TABLE RENTSYSTEM CASCADE CONSTRAINTS;
DROP TABLE SEAT CASCADE CONSTRAINTS;
DROP TABLE PURCHASE CASCADE CONSTRAINTS;
DROP TABLE PAYMENT CASCADE CONSTRAINTS;
DROP TABLE RENTAPPLICATION CASCADE CONSTRAINTS;
DROP TABLE PERFORMANCE CASCADE CONSTRAINTS;
DROP TABLE HALL CASCADE CONSTRAINTS;
DROP TABLE MEMBER CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_MNO;
DROP SEQUENCE SEQ_PERFONO;
DROP SEQUENCE SEQ_RENTALNO;
DROP SEQUENCE SEQ_SEATNO;
DROP SEQUENCE SEQ_PAYNO;
DROP SEQUENCE SEQ_PURCHASENO;
DROP SEQUENCE SEQ_REVIEWNO;

--------------------------------------------------
----------------  회원 관련	 ---------------------
--------------------------------------------------
CREATE TABLE MEMBER (
	USER_ID	    VARCHAR2(30) PRIMARY KEY,
    USER_PWD	VARCHAR2(100) NOT NULL,
	USER_NAME	VARCHAR2(15) NOT NULL,
	USER_PHONE	VARCHAR2(30) NOT NULL UNIQUE,
    USER_EMAIL	VARCHAR2(100) NOT NULL UNIQUE,
	USER_GRADE  VARCHAR2(10) DEFAULT '회원' CHECK (USER_GRADE IN('회원','관리자')),
	ENROLL_DATE	DATE DEFAULT SYSDATE,
    UPDATE_DATE DATE NULL,
	STATUS	VARCHAR2(1) DEFAULT 'Y' CHECK (STATUS IN('Y', 'N'))
);
COMMENT ON COLUMN MEMBER.USER_ID IS '회원아이디';
COMMENT ON COLUMN MEMBER.USER_PWD IS '회원비밀번호';
COMMENT ON COLUMN MEMBER.USER_NAME IS '회원이름';
COMMENT ON COLUMN MEMBER.USER_PHONE IS '핸드폰번호';
COMMENT ON COLUMN MEMBER.USER_EMAIL IS '이메일';
COMMENT ON COLUMN MEMBER.USER_GRADE IS '회원등급';
COMMENT ON COLUMN MEMBER.ENROLL_DATE IS '회원가입일';
COMMENT ON COLUMN MEMBER.UPDATE_DATE IS '회원수정일';
COMMENT ON COLUMN MEMBER.STATUS IS '회원등록여부(Y/N)';

CREATE SEQUENCE SEQ_MNO
NOCACHE;

INSERT INTO MEMBER --관리자 샘플
VALUES ('admin', '1234', '관리자', '01011112222', 'admin@khor.kr', '관리자', DEFAULT, null, DEFAULT);
INSERT INTO MEMBER --일반 샘플
VALUES ('user1', 'pass1', '김일반', '01011113333', 'user01@khor.kr', DEFAULT, DEFAULT, null, DEFAULT);
INSERT INTO MEMBER --일반 샘플
VALUES ('user2', 'pass2', '최일반', '01011114444', 'user02@khor.kr', DEFAULT, DEFAULT, null, DEFAULT);
INSERT INTO MEMBER --일반 샘플
VALUES ('user3', 'pass3', '나일반', '01011115555', 'user03@khor.kr', DEFAULT, DEFAULT, null, DEFAULT);
INSERT INTO MEMBER --일반 샘플
VALUES ('user4', 'pass4', '박일반', '01011116666', 'user04@khor.kr', DEFAULT, DEFAULT, null, DEFAULT);
INSERT INTO MEMBER --일반 샘플
VALUES ('user5', 'pass5', '이일반', '01011117777', 'user05@khor.kr', DEFAULT, DEFAULT, null, DEFAULT);
INSERT INTO MEMBER --일반 샘플
VALUES ('user6', 'pass6', '서일반', '01011118888', 'user06@khor.kr', DEFAULT, DEFAULT, null, DEFAULT);
INSERT INTO MEMBER --일반 샘플
VALUES ('user7', 'pass7', '한일반', '01011119999', 'user07@khor.kr', DEFAULT, DEFAULT, null, DEFAULT);
INSERT INTO MEMBER --일반 샘플
VALUES ('user8', 'pass8', '정일반', '01011111010', 'user08@khor.kr', DEFAULT, DEFAULT, null, DEFAULT);
INSERT INTO MEMBER --일반 샘플
VALUES ('user9', 'pass9', '추일반', '01011111111', 'user09@khor.kr', DEFAULT, DEFAULT, null, DEFAULT);
INSERT INTO MEMBER --일반 샘플
VALUES ('user10', 'pass10', '차일반', '01011111212', 'user10@khor.kr', DEFAULT, DEFAULT, null, DEFAULT);

--------------------------------------------------
----------------  공연홀 관련	 ---------------------
--------------------------------------------------
CREATE TABLE HALL (
	HALL_NAME	VARCHAR2(50) PRIMARY KEY,
	HALL_SEATS	NUMBER NOT NULL,
	HALL_LOCATION VARCHAR2(30) NULL
);
COMMENT ON COLUMN HALL.HALL_NAME IS '공연홀이름';
COMMENT ON COLUMN HALL.HALL_SEATS IS '공연홀 총 좌석수';
COMMENT ON COLUMN HALL.HALL_LOCATION IS '공연홀위치';

INSERT INTO HALL --공연홀 샘플
VALUES ('A', 100, '서울시 어딘가');
INSERT INTO HALL --공연홀 샘플
VALUES ('B', 200, '서울시 어딘가');

--------------------------------------------------
----------------  대관신청서 관련	 -----------------
--------------------------------------------------
CREATE TABLE RENTAPPLICATION (
	RENTAL_CODE NUMBER PRIMARY KEY,
	HALL_NAME	VARCHAR2(50) NOT NULL,
	COVENANTEE_NAME	VARCHAR2(20) NOT NULL,
	COVENANTEE_PHONE VARCHAR2(30) NOT NULL,
	AGENT_NAME VARCHAR2(20) NOT NULL,
	AGENT_PHONE	VARCHAR2(30) NOT NULL,
	AGENT_EMAIL	VARCHAR2(50) NOT NULL,
	RENTAL_START_DATE DATE NOT NULL,
	RENTAL_END_DATE	DATE NOT NULL,
	RENTAL_PROPOSE VARCHAR2(40) NOT NULL,
	RENTAL_DATE	DATE DEFAULT SYSDATE,
	APPROVE_STATUS VARCHAR2(20) DEFAULT '승인대기' CHECK (APPROVE_STATUS IN('승인대기','미승인','승인')),
    FOREIGN KEY (HALL_NAME) REFERENCES HALL(HALL_NAME)
);
COMMENT ON COLUMN RENTAPPLICATION.RENTAL_CODE IS '대관예약코드';
COMMENT ON COLUMN RENTAPPLICATION.HALL_NAME IS '공연홀이름';
COMMENT ON COLUMN RENTAPPLICATION.COVENANTEE_NAME IS '대관대표자명';
COMMENT ON COLUMN RENTAPPLICATION.COVENANTEE_PHONE IS '대표자연락처';
COMMENT ON COLUMN RENTAPPLICATION.AGENT_NAME IS '담당자이름';
COMMENT ON COLUMN RENTAPPLICATION.AGENT_PHONE IS '담당자연락처';
COMMENT ON COLUMN RENTAPPLICATION.AGENT_EMAIL IS '담당자메일주소';
COMMENT ON COLUMN RENTAPPLICATION.RENTAL_START_DATE IS '대관시작일';
COMMENT ON COLUMN RENTAPPLICATION.RENTAL_END_DATE IS '대관종료일';
COMMENT ON COLUMN RENTAPPLICATION.RENTAL_PROPOSE IS '대관공연명';
COMMENT ON COLUMN RENTAPPLICATION.RENTAL_DATE IS '대관신청일';
COMMENT ON COLUMN RENTAPPLICATION.APPROVE_STATUS IS '승인여부';

CREATE SEQUENCE SEQ_RENTALNO
NOCACHE;

INSERT INTO RENTAPPLICATION --대관신청서 샘플
VALUES (1, 'A', '김대표','01022222222','김담당','01033333333','damdangkim@khor.kr','23/1/1','23/1/1','달에서 온 그대',DEFAULT,DEFAULT);
INSERT INTO RENTAPPLICATION --대관신청서 샘플
VALUES (2, 'A', '나대표','01022222223','나담당','01033333334','damdangna@khor.kr','23/1/15','23/1/15','태양에서 온 그대',DEFAULT,DEFAULT);
INSERT INTO RENTAPPLICATION --대관신청서 샘플
VALUES (3, 'B', '박대표','01022222224','박담당','01033333335','damdangpark@khor.kr','23/2/1','23/2/1','화성에서 온 그대',DEFAULT,DEFAULT);
INSERT INTO RENTAPPLICATION --대관신청서 샘플
VALUES (4, 'B', '이대표','01022222225','이담당','01033333336','damdanglee@khor.kr','23/2/15','23/2/15','목성에서 온 그대',DEFAULT,DEFAULT);

--------------------------------------------------
----------------  공연 관련	 ---------------------
--------------------------------------------------
CREATE TABLE PERFORMANCE (
	PERFO_NO NUMBER PRIMARY KEY,
    RENTAL_CODE NUMBER NOT NULL,
	PERFO_TITLE	VARCHAR2(200) NOT NULL,
    GENRE_NAME	VARCHAR2(50) NOT NULL,
	PERFO_START_DATE DATE NOT NULL,
	PERFO_END_DATE DATE NOT NULL,
	DIRECTO VARCHAR2(50) NULL,
	CAST VARCHAR2(1000) NULL,
	PERFO_CONTENT VARCHAR2(1000) NULL,
	RUNNING_TIME VARCHAR2(50) NULL,
	AGE_LIMIT NUMBER NULL,
	PERFO_STATUS VARCHAR2(1) DEFAULT 'Y' CHECK (PERFO_STATUS IN('Y', 'N')),
	PRICE NUMBER NOT NULL,
    FOREIGN KEY (RENTAL_CODE) REFERENCES RENTAPPLICATION (RENTAL_CODE)
);
COMMENT ON COLUMN PERFORMANCE.PERFO_NO IS '공연번호';
COMMENT ON COLUMN PERFORMANCE.RENTAL_CODE IS '대관예약코드';
COMMENT ON COLUMN PERFORMANCE.PERFO_TITLE IS '제목';
COMMENT ON COLUMN PERFORMANCE.GENRE_NAME IS '장르';
COMMENT ON COLUMN PERFORMANCE.PERFO_START_DATE IS '공연시작날짜';
COMMENT ON COLUMN PERFORMANCE.PERFO_END_DATE IS '공연끝날짜';
COMMENT ON COLUMN PERFORMANCE.DIRECTO IS '총감독';
COMMENT ON COLUMN PERFORMANCE.CAST IS '출연진';
COMMENT ON COLUMN PERFORMANCE.PERFO_CONTENT IS '내용(소개글)';
COMMENT ON COLUMN PERFORMANCE.RUNNING_TIME IS '러닝타임';
COMMENT ON COLUMN PERFORMANCE.AGE_LIMIT IS '연령제한';
COMMENT ON COLUMN PERFORMANCE.PERFO_STATUS IS '상태값';
COMMENT ON COLUMN PERFORMANCE.PRICE IS '공연가격';

CREATE SEQUENCE SEQ_PERFONO
NOCACHE;

INSERT INTO PERFORMANCE --공연 샘플
VALUES (1, 1, '달에서 온 그대','멜로','23/1/1','23/1/10','김감독','김출연A,김출연B','달에서 왔다','100분',19,DEFAULT,20000);
INSERT INTO PERFORMANCE --공연 샘플
VALUES (2, 2, '태양에서 온 그대','스릴러','23/1/15','23/1/25','나감독','나출연A,나출연B','태양에서 왔다','120분',19,DEFAULT,40000);
INSERT INTO PERFORMANCE --공연 샘플
VALUES (3, 3, '화성에서 온 그대','공포','23/2/1','23/2/10','박감독','박출연A,박출연B','화성에서 왔다','140분',19,DEFAULT,60000);
INSERT INTO PERFORMANCE --공연 샘플
VALUES (4, 4, '목성에서 온 그대','미스터리','23/2/15','23/2/25','이감독','이출연A,이출연B','목성에서 왔다','160분',19,DEFAULT,80000);

--------------------------------------------------
----------------  리뷰 관련	 ---------------------
--------------------------------------------------
CREATE TABLE REVIEW (
	REVIEW_NO NUMBER PRIMARY KEY,
	PERFO_NO NUMBER	NOT NULL,
	CONTENT	VARCHAR2(1000) NULL,
	WRITE_DATE DATE DEFAULT SYSDATE	NULL,
    FOREIGN KEY (PERFO_NO) REFERENCES PERFORMANCE (PERFO_NO)
);
COMMENT ON COLUMN REVIEW.REVIEW_NO IS '리뷰고유번호';
COMMENT ON COLUMN REVIEW.PERFO_NO IS '공연번호';
COMMENT ON COLUMN REVIEW.CONTENT IS '리뷰내용';
COMMENT ON COLUMN REVIEW.WRITE_DATE IS '작성일';

CREATE SEQUENCE SEQ_REVIEWNO
NOCACHE;

INSERT INTO REVIEW --리뷰 샘플
VALUES (SEQ_REVIEWNO.NEXTVAL, 1, '진짜 달에서 왔네요', DEFAULT);
INSERT INTO REVIEW --리뷰 샘플
VALUES (SEQ_REVIEWNO.NEXTVAL, 1, '달 가고 싶어요', DEFAULT);
INSERT INTO REVIEW --리뷰 샘플
VALUES (SEQ_REVIEWNO.NEXTVAL, 2, '진짜 태양에서 왔네요', DEFAULT);
INSERT INTO REVIEW --리뷰 샘플
VALUES (SEQ_REVIEWNO.NEXTVAL, 2, '태양의 후예 보고 싶어요', DEFAULT);
INSERT INTO REVIEW --리뷰 샘플
VALUES (SEQ_REVIEWNO.NEXTVAL, 3, '진짜 화성에서 왔네요', DEFAULT);
INSERT INTO REVIEW --리뷰 샘플
VALUES (SEQ_REVIEWNO.NEXTVAL, 3, '화내지마성', DEFAULT);
INSERT INTO REVIEW --리뷰 샘플
VALUES (SEQ_REVIEWNO.NEXTVAL, 4, '진짜 목성에서 왔네요', DEFAULT);
INSERT INTO REVIEW --리뷰 샘플
VALUES (SEQ_REVIEWNO.NEXTVAL, 4, '목성아 그러면 목성', DEFAULT);

--------------------------------------------------
----------------  대관 관련	 ---------------------
--------------------------------------------------
CREATE TABLE RENTSYSTEM (
	RENTAL_CODE	NUMBER PRIMARY KEY,
    USER_ID	    VARCHAR2(50) NOT NULL,
	PERFO_NO	NUMBER		 NOT NULL,
	HALL_STATUS	VARCHAR2(30) DEFAULT '대관중' CHECK (HALL_STATUS IN('대관중','대관종료')),
    FOREIGN KEY (RENTAL_CODE) REFERENCES RENTAPPLICATION (RENTAL_CODE),
    FOREIGN KEY (PERFO_NO) REFERENCES PERFORMANCE (PERFO_NO),
    FOREIGN KEY (USER_ID) REFERENCES MEMBER (USER_ID)
);
COMMENT ON COLUMN RENTSYSTEM.RENTAL_CODE IS '대관예약코드';
COMMENT ON COLUMN RENTSYSTEM.RENTAL_CODE IS '회원아이디';
COMMENT ON COLUMN RENTSYSTEM.PERFO_NO IS '공연번호';
COMMENT ON COLUMN RENTSYSTEM.HALL_STATUS IS '대관상태';

INSERT INTO RENTSYSTEM --대관 샘플
VALUES (1, 'user1', 1, '대관종료');
INSERT INTO RENTSYSTEM --대관 샘플
VALUES (2, 'user2', 2, DEFAULT);
INSERT INTO RENTSYSTEM --대관 샘플
VALUES (3, 'user3', 3, DEFAULT);
INSERT INTO RENTSYSTEM --대관 샘플
VALUES (4, 'user4', 4, DEFAULT);

--------------------------------------------------
----------------  좌석 관련	 ---------------------
--------------------------------------------------
CREATE TABLE SEAT (
	SEAT_NO	NUMBER PRIMARY KEY,
    SEAT_CODE	VARCHAR2(20) NOT NULL,
	HALL_NAME	VARCHAR2(50) NOT NULL,
	SEAT_TIER	VARCHAR2(20) NOT NULL,
	SEAT_PRICE	NUMBER NOT NULL,
	SEAT_STATUS	VARCHAR2(1) DEFAULT 'Y' CHECK (SEAT_STATUS IN('Y', 'N')),
    FOREIGN KEY (HALL_NAME) REFERENCES HALL (HALL_NAME)
);
COMMENT ON COLUMN SEAT.SEAT_NO IS '좌석고유번호';
COMMENT ON COLUMN SEAT.SEAT_CODE IS '좌석코드';
COMMENT ON COLUMN SEAT.HALL_NAME IS '공연홀이름';
COMMENT ON COLUMN SEAT.SEAT_TIER IS '좌석등급';
COMMENT ON COLUMN SEAT.SEAT_PRICE IS '좌석가격';
COMMENT ON COLUMN SEAT.SEAT_STATUS IS '좌석상태';

CREATE SEQUENCE SEQ_SEATNO
NOCACHE;

INSERT INTO SEAT --좌석 샘플
VALUES (SEQ_SEATNO.NEXTVAL,'A1', 'A', 'R', 50000, DEFAULT);
INSERT INTO SEAT --좌석 샘플
VALUES (SEQ_SEATNO.NEXTVAL,'A2', 'A', 'R', 50000, DEFAULT);
INSERT INTO SEAT --좌석 샘플
VALUES (SEQ_SEATNO.NEXTVAL,'A3', 'A', 'R', 50000, DEFAULT);
INSERT INTO SEAT --좌석 샘플
VALUES (SEQ_SEATNO.NEXTVAL,'A4', 'A', 'R', 50000, DEFAULT);
INSERT INTO SEAT --좌석 샘플
VALUES (SEQ_SEATNO.NEXTVAL,'A5', 'A', 'R', 50000, DEFAULT);
INSERT INTO SEAT --좌석 샘플
VALUES (SEQ_SEATNO.NEXTVAL,'B1', 'A', 'S', 30000, DEFAULT);
INSERT INTO SEAT --좌석 샘플
VALUES (SEQ_SEATNO.NEXTVAL,'B2', 'A', 'S', 30000, DEFAULT);
INSERT INTO SEAT --좌석 샘플
VALUES (SEQ_SEATNO.NEXTVAL,'C22', 'A', 'A', 10000, DEFAULT);
INSERT INTO SEAT --좌석 샘플
VALUES (SEQ_SEATNO.NEXTVAL,'A1', 'B', 'R', 50000, DEFAULT);
INSERT INTO SEAT --좌석 샘플
VALUES (SEQ_SEATNO.NEXTVAL,'A2', 'B', 'R', 50000, DEFAULT);
INSERT INTO SEAT --좌석 샘플
VALUES (SEQ_SEATNO.NEXTVAL,'A3', 'B', 'R', 50000, DEFAULT);

--------------------------------------------------
----------------  결제 관련	 ---------------------
--------------------------------------------------
CREATE TABLE PAYMENT (
	PAYMENT_NO	NUMBER PRIMARY KEY,
    USER_ID	    VARCHAR2(50) NOT NULL,
	PAYMENT_METHOD VARCHAR2(50) NOT NULL,
	PAYMENT_DATE DATE DEFAULT SYSDATE,
	PAYMENT_STATUS VARCHAR2(20)	DEFAULT '결제대기' CHECK (PAYMENT_STATUS IN('결제대기','결제완료')),
	PAYMENT_AMOUNT NUMBER NOT NULL,
	DEPOSIT_NAME VARCHAR2(20) NULL,
	DEPOSIT_BANK VARCHAR2(20) NULL,
	CARDCO_NAME	VARCHAR2(20) NULL,
	CARD_NO	NUMBER NULL,
    FOREIGN KEY (USER_ID) REFERENCES MEMBER (USER_ID)
);
COMMENT ON COLUMN PAYMENT.PAYMENT_NO IS '결제코드';
COMMENT ON COLUMN PAYMENT.USER_ID IS '회원아이디';
COMMENT ON COLUMN PAYMENT.PAYMENT_METHOD IS '결제수단';
COMMENT ON COLUMN PAYMENT.PAYMENT_DATE IS '결제일';
COMMENT ON COLUMN PAYMENT.PAYMENT_STATUS IS '결제상태';
COMMENT ON COLUMN PAYMENT.PAYMENT_AMOUNT IS '결제금액';
COMMENT ON COLUMN PAYMENT.DEPOSIT_NAME IS '입금자명';
COMMENT ON COLUMN PAYMENT.DEPOSIT_BANK IS '입금은행';
COMMENT ON COLUMN PAYMENT.CARDCO_NAME IS '카드회사';
COMMENT ON COLUMN PAYMENT.CARD_NO IS '카드번호';

CREATE SEQUENCE SEQ_PAYNO
NOCACHE;

INSERT INTO PAYMENT --결제 샘플
VALUES (SEQ_PAYNO.NEXTVAL,'user7', '신용카드', DEFAULT, DEFAULT, 50000, NULL,NULL,'현대카드',1234567812345678);
INSERT INTO PAYMENT --결제 샘플
VALUES (SEQ_PAYNO.NEXTVAL,'user8', '신용카드', DEFAULT, DEFAULT, 10000, NULL,NULL,'신한카드',1234567812349876);
INSERT INTO PAYMENT --결제 샘플
VALUES (SEQ_PAYNO.NEXTVAL,'user9', '무통장', DEFAULT, DEFAULT, 30000, '추일반', 'KB국민', NULL, NULL);
INSERT INTO PAYMENT --결제 샘플
VALUES (SEQ_PAYNO.NEXTVAL,'user10', '신용카드', DEFAULT, DEFAULT, 50000, NULL,NULL,'BC카드',1234567812345432);

--------------------------------------------------
----------------  예매 관련	 ---------------------
--------------------------------------------------
CREATE TABLE PURCHASE (
	PURCHASE_NO	NUMBER PRIMARY KEY,
	USER_ID	    VARCHAR2(50) NOT NULL,
	RENTAL_CODE	NUMBER NOT NULL,
	SEAT_NO	    NUMBER NOT NULL,
    PAYMENT_NO	NUMBER NOT NULL,
	CUSTOMERSERVICE_STATUS	VARCHAR2(20) NULL,
	PURCHASE_DATE DATE DEFAULT SYSDATE,
	RESERVATION_DATE DATE NOT NULL,
    TOTAL_PRICE	NUMBER NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES MEMBER(USER_ID),
    FOREIGN KEY (RENTAL_CODE) REFERENCES RENTSYSTEM (RENTAL_CODE),
    FOREIGN KEY (PAYMENT_NO) REFERENCES PAYMENT (PAYMENT_NO),
    FOREIGN KEY (SEAT_NO) REFERENCES SEAT (SEAT_NO)
);
COMMENT ON COLUMN PURCHASE.PURCHASE_NO IS '예매코드';
COMMENT ON COLUMN PURCHASE.USER_ID IS '회원아이디';
COMMENT ON COLUMN PURCHASE.RENTAL_CODE IS '대관예약코드';
COMMENT ON COLUMN PURCHASE.SEAT_NO IS '좌석코드';
COMMENT ON COLUMN PURCHASE.PAYMENT_NO IS '결제코드';
COMMENT ON COLUMN PURCHASE.CUSTOMERSERVICE_STATUS IS 'CS상태';
COMMENT ON COLUMN PURCHASE.PURCHASE_DATE IS '구매날짜';
COMMENT ON COLUMN PURCHASE.RESERVATION_DATE IS '예약날짜';
COMMENT ON COLUMN PURCHASE.TOTAL_PRICE IS '총 가격';

CREATE SEQUENCE SEQ_PURCHASENO
NOCACHE;

INSERT INTO PURCHASE --예매 샘플
VALUES (SEQ_PURCHASENO.NEXTVAL,'user7', 2, 4, 1, NULL, DEFAULT, '23/1/20', 50000);
INSERT INTO PURCHASE --예매 샘플
VALUES (SEQ_PURCHASENO.NEXTVAL,'user8', 4, 8, 2, NULL, DEFAULT, '23/2/22', 10000);
INSERT INTO PURCHASE --예매 샘플
VALUES (SEQ_PURCHASENO.NEXTVAL,'user9', 3, 7, 3, NULL, DEFAULT, '23/2/9', 30000);
INSERT INTO PURCHASE --예매 샘플
VALUES (SEQ_PURCHASENO.NEXTVAL,'user10', 2, 10, 4, NULL, DEFAULT, '23/1/21', 50000);

COMMIT;




























